- name: Check if NATS Server package is installed
  shell: "dpkg-query -W -f='${Version}' nats-server | grep {{ nats_version }}"
  register: is_installed
  check_mode: no
  failed_when: no
  changed_when: no

- name: Install NATS Server package from GitHub
  apt:
    state: present
    deb: "https://github.com/nats-io/nats-server/releases/download/v{{ nats_version }}/nats-server-v{{ nats_version }}-amd64.deb"
  when: is_installed.rc == 1

- name: Ensure NATS Server service file is available
  template:
    src: nats-server.service.j2
    dest: /etc/systemd/system/nats-server.service
    mode: 0644
  register: nats_server_service_template

- name: Reload systemd after adding NATS Server service file
  systemd:
    state: stopped
    daemon_reload: true
    name: nats-server
  when: nats_server_service_template.changed

- name: Create NATS Server custom configs directory
  file:
    path: /etc/nats-server/conf.d
    state: directory

- name: Create NATS Server main configuration file
  template:
    src: nats-server.conf.j2
    dest: /etc/nats-server/nats-server.conf.conf
    mode: 0644
  notify: restart nats-server

- name: Create NATS Server custom configuration files
  template:
    src: "{{ item }}.j2"
    dest: "/etc/nats-server/conf.d/{{ item.split('/')[-1] }}"
    mode: 0644
  with_items: "{{ nats_custom_conf }}"
  notify: restart nats-server

- name: Ensure NATS Server service is started and enabled on boot
  service:
    name: nats-server
    state: started
    enabled: true
